### ISSUE TITLE
Feature: User can read about an art piece. 

### ISSUE THREAD

**Issue by valentina-osorio5** [valentina-osorio5/Front-end-project-Valentina-Arteye-App#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can read about an art piece. When they press the eye button or refresh the page, a new art piece is shown. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

![Screen Shot 2024-11-25 at 2 47 05 PM](https://github.com/user-attachments/assets/ead8a709-b735-4308-97ed-0c2facf71749)

## ✅ Task List

- [x] Design layout to match figma files.
- [x] Hardcode design into HTML.
- [x] Fetch function should only display art pieces with an image. 
- [x] Eye button should refresh page and show new piece of art. 
- [x] Make sure layout is responsive on mobile and desktop screens. 
- [ ] 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
