### ISSUE TITLE
Feature: User can favorite art pieces to save them and refer to them later.

### ISSUE THREAD

**Issue by valentina-osorio5** [valentina-osorio5/Front-end-project-Valentina-Arteye-App#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favorite art pieces to save them and refer to them later.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User presses heart button which saves the art piece in their saved view. This view can be accessed from the menu tab. 

## 🖼️ Wireframes

![Screen Shot 2024-11-25 at 3 17 27 PM](https://github.com/user-attachments/assets/ec5b2cc6-60b2-4649-9726-116a9a4c55a4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can press heart button, button turns to pink. 
- [x] Art piece and information is saved to local storage. 
- [ ] User can view swap to saved entries. 
- [x] Should display as "nothing saved yet" when no entries are saved. 
- [x] Saved entries view is navigated through the menu, which pops up when hovered. 
- [x] Saved entries can be viewed. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
