### ISSUE TITLE
Feature: User can unfavorite the art piece if they no longer want to save them in the app. 

### ISSUE THREAD

**Issue by valentina-osorio5** [valentina-osorio5/Front-end-project-Valentina-Arteye-App#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can unfavorite the art piece if they no longer want to save them in the app. 

## 📐 Functionality

User can unfavorite the art piece if they no longer want to save them in the app. 

Users can unfavorite or "delete" a saved entry from the saved pieces view. 

## 🖼️ Wireframes

![Screen Shot 2024-11-25 at 3 18 33 PM](https://github.com/user-attachments/assets/8be4977e-a548-4f49-9b0a-e705a413b231)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Viewer can unfavorite an art piece. 
- [ ] When heart is clicked, a pop up modal appears confirming you want to unfavorite the art-piece. 
- [ ] Once piece is unfavorited, it is deleted from the dom and from local storage. 
- [ ] Viewer is brought to see all of the saved entries, if none toggle view no saves. 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
